### ISSUE TITLE
ImportError: No module named 'metrics'

### ISSUE THREAD

**Issue by c1a1o1** [sumuzhao/CycleGAN-Music-Style-Transfer#9]
E:\Users\Raytine\Anaconda3\python.exe F:/voice/CycleGAN-Music-Style-Transfer-master/main.py --dataset_A_dir='data/JC_J' --dataset_B_dir='data/JC_C' --type='cyclegan' --model='base' --sigma_d=0 --phase='train'
Traceback (most recent call last):
  File "F:/voice/CycleGAN-Music-Style-Transfer-master/main.py", line 4, in <module>
    from model import cyclegan
  File "F:\voice\CycleGAN-Music-Style-Transfer-master\model.py", line 13, in <module>
    from metrics import *
ImportError: No module named 'metrics'

**Comment by esemeniuc** [comment]
See https://github.com/sumuzhao/CycleGAN-Music-Style-Transfer/pull/10
